繳交 part 3 作業（另昨日有詢問老師關於instance reachability check failed)
JhanJoe/jjwhtwo pull request #4
Opened 2024-06-15 07:46 UTC by JhanJoe

老師您好，我是詹硯喬
part 3 作業如下
http://34.211.150.241:8000/
http://34.211.150.241:8000/attraction/10

--------------

另外昨天有問老師關於我的ec2出現 instance reachability check failed 的問題
第一次發生這個問題是在上上週，那時我同時開了瀏覽器上的ec2連線和本地的vscode遠端連線
我在想那時是不是反覆從不同地方連線導致他爆掉(?)

第二次發生是在昨天，那時我只用vscode遠端連線，不知道是不是我連線一直沒有斷掉（會有連線太久自動登出的問題嗎？），總之他後來自己重新連線了1次（有成功連線），
大概過了幾個小時我執行了git pull和再次啟動uvicorn，那時看狀態欄應該是有成功執行起來，但後來就當機了，然後我的頁面也掛了。
再回頭進ec2的儀表板，就看到他system status checks是ok的，但instance status checks變成了紅字-instance reachability check failed，即使ec2的狀態仍顯示"執行中"，但想連線進終端機卻怎麼樣都連不上

我查了滿多網站，說導致這種情況發生的原因可能有很多，不過我推測我這裡壞掉的原因是CPU在某段時間運行到100%（看ec2的後台資料看到的）
https://repost.aws/zh-Hant/knowledge-center/ec2-linux-resource-over-utilization

許多網友說解決辦法是停止再重啟就對了(?) 
如果頻繁發生可能就是要重建ec2
https://stackoverflow.com/questions/75284057/how-to-fix-instance-reachability-check-failed-status-error-in-ec2-instance

不好意思，再麻煩老師了

2024-06-15 17:59 UTC, cwpeng requested changes
- There is a separating line between navigation bar and attraction image in desktop layout.
- Take attention on details: color and border.
![34 211 150 241_8000_attraction_10](https://github.com/JhanJoe/jjwhtwo/assets/6104683/9ba62329-8f7e-482c-8440-ab4fb152c6d1)

I have reviewed your backend code again, so far, I think everything is fine, no obvious bad code.

2024-06-16 08:57 UTC, JhanJoe commented
謝謝老師協助檢查code問題，之後如果遇到EC2再次因為類似原因掛掉那我還是就先重啟處理

另外您提到的幾個部分
我做了修改，再麻煩老師確認了，謝謝您!

<img width="748" alt="螢幕擷取畫面 2024-06-16 165719" src="https://github.com/JhanJoe/jjwhtwo/assets/158795896/48e0db00-2882-41ab-98c2-7443810ec978">

2024-06-16 11:23 UTC, cwpeng requested changes
There is no space between navigation bar and image in mobile layout.
![34 211 150 241_8000_attraction_10](https://github.com/JhanJoe/jjwhtwo/assets/6104683/8a6f072b-058c-46a3-b7e7-09104353eb18)

2024-06-16 13:02 UTC, JhanJoe commented
謝謝老師提醒，我調整了navbar的space和RWD時圖片沒有滿版的部分
並再檢查了一些其他地方，調整了一些css
不好意思再麻煩您了，謝謝!
http://34.211.150.241:8000/
http://34.211.150.241:8000/attraction/10

<img width="269" alt="螢幕擷取畫面 2024-06-16 205836" src="https://github.com/JhanJoe/jjwhtwo/assets/158795896/f9b92897-d00c-4611-bd7f-52fb68840f81">

2024-06-16 14:25 UTC, cwpeng approved these changes
Good. Done.

2024-06-16 14:32 UTC, JhanJoe commented
感謝老師!!

2024-06-16 14:32 UTC, merged